# Generated by Django 2.1.4 on 2019-01-02 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_auto_20181226_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
